### ISSUE TITLE
Using Honeybadger with Quartz Scheduler

### ISSUE THREAD

**Issue by navinpai** [honeybadger-io/honeybadger-java#151]
Hey, I'm using `Honeybadger-Java` integration in a project that uses [Quartz](http://www.quartz-scheduler.org/) and had an issue. The way Quartz works is by spawning new threads for scheduled jobs. The issue I have is that I am unable to get Honeybadger to catch any exceptions on the spawned threads, even if I attach the Honeybadger Exception Handler to the scheduled job.

Example code is here below:

```
public class SyncSchedulerService {

    public static void main(String[] args) throws SchedulerException {
        HoneybadgerUncaughtExceptionHandler.registerAsUncaughtExceptionHandler();
        
        // Exceptions added in the scheduling class log to Honeybadger correctly
        // throw new MyException("This is an Exception");
        
        SchedulerFactory sf = new StdSchedulerFactory();
        Scheduler sched = sf.getScheduler();

        JobDetail job = newJob(MyJob.class)
                .withIdentity("blah", "blah")
                .build();

        Trigger trigger = TriggerBuilder.newTrigger()
                .withIdentity("blah", "blah")
                .startNow()
                .withSchedule(SimpleScheduleBuilder.simpleSchedule()
                .repeatForever())
                .build();

        sched.scheduleJob(job, trigger2);
    }
}
```

```
public class MyJob implements Job {
    public void execute(JobExecutionContext context) throws JobExecutionException {
       
        HoneybadgerUncaughtExceptionHandler.registerAsUncaughtExceptionHandler();

        // Exceptions added in the job class DO NOT GET LOGGED to Honeybadger
        // throw new JobExecutionException(new MyException("This is an Exception"));
    }
}
```

Exceptions in the quartz scheduling class get logged correctly, but those in the scheduled class simply do not get logged into Honeybadger. I'm unable to figure out why this is because I've even called `registerAsUncaughtExceptionHandler()` in the job class. Any idea why this is happening and how I can get Honeybadger integration to work in threaded environments like this?

Thanks!

**Comment by joshuap** [comment]
@JasonTrue any ideas on this one?

**Comment by JasonTrue** [comment]
I don't have any experience with Quartz, but at first glance, my guess based on a cursory reading of Quartz documentation is that JobExecutionException is likely to something that is caught by Quartz, so I wouldn't expect it to bubble up to the Uncaught Exception Handler.

If my understanding is correct, then I would guess that the happy-path might be to have a base class for your jobs that catch Throwable and call the Honeybadger Notify API call, or perhaps implement an JobListener and do the same thing.

**Comment by navinpai** [comment]
Haha... Ended up doing just that and that worked perfectly! Thanks @JasonTrue 😸 

Going ahead and closing this issue
