### ISSUE TITLE
Add exception causes to error payload

### ISSUE THREAD

**Issue by dekobon** [honeybadger-io/honeybadger-java#2]
Causes should look like this in the payload: 
```json
{ "error" : 
    {"causes" : 
        [ { class : "ExceptionClass", 
            message : "Exception message", 
            backtrace:[{number: 1, file: "foo.java", method: "Bar"}, {}, ...]}]}}
```
All the cause data is basically identical to the data we send about the top exception which was thrown, but limited to class, message and backtrace. We don't currently display these in the UI but it's something I want to work on.

Yep, nested/chained exceptions. In Ruby they are called "Causes", but I think they'll work here too. We don't nest them in the payload, we just send them in the order they were chained. This is how I construct them in Ruby: https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/notice.rb#L440

**Comment by joshuap** [comment]
See comment on #3 about application context.

**Comment by dekobon** [comment]
@joshuap what order should the causes be populated? Should the root cause come first or last?

**Comment by joshuap** [comment]
The root cause should be last.

**Comment by dekobon** [comment]
The next question is - should the root exception be stored in the list of causes or not? I assume not.

**Comment by joshuap** [comment]
Nope! The root exception is the normal error message/class/backtrace at the top level of the error payload.
