### ISSUE TITLE
Add server properties - stats, pid, etc

### ISSUE THREAD

**Issue by dekobon** [honeybadger-io/honeybadger-java#22]

**Comment by joshuap** [comment]
:+1:

**Comment by dekobon** [comment]
@joshuap What format is server.time supposed to be in? Epoch seconds? Epoch milliseconds? ISO?

**Comment by dekobon** [comment]
@joshuap Can you better define these values from stats for me? I've noted how I'm assuming that they are used.

stats / mem:
 * total - total amount of memory used
 * free - total amount of memory available
 * buffers - not possible to get in the JVM, but I'm unsure about what this means, so I may be wrong.
 * cached - not possible to get in the JVM, but I'm unsure about what this means, so I may be wrong.
 * free total

Also, you may want two sets of values. You may want everything above, but prefixed with vm_ because the virtual machine or bytecode/opcode runtime may have different memory settings than the OS.

You may want to make buffers and cached optional in the json schema.

As for load, the JVM can only return a value for one. In Linux, I can get the values from /proc/loadavg but in other OSes it is not possible. I recommend changing the schema such that five and fifteen are optional.

**Comment by joshuap** [comment]
@dekobon on Linux all the memory info comes from */proc/meminfo*. MemTotal, MemFree, Buffers and Cached are all entries in that file. The "free total" is calculated by MemFree+Buffers+Cached. For now let's just report the system stats (vs. the vm_ stats). Maybe we'll add vm_ in the future. If you can't get buffers/cached I guess you could just report zeros for those values, assuming free is the actual total memory available (just report the same value for free_total so that we have it). I will also consider making buffers/cached optional so that we can hide them on our end (zeroing them out is fine for now though).

Regarding the load, OK, let's make five/fifteen optional. I'll update the schema.

**Comment by joshuap** [comment]
Actually, can you send five/fifteen as null rather than completely omitting them?

**Comment by joshuap** [comment]
Let's also make buffers/cached null if they aren't available.

**Comment by joshuap** [comment]
Re: server.time -- ISO 8601.

**Comment by dekobon** [comment]
When not on Linux, calculating load and memory usage for the OS becomes
more dicey. You will need to invoke things like: free, w, kstats, etc if
you are running on OS X or Solaris/IllumOS/SmartOS. I'm not sure what
utilities you need to invoke for FreeBSD and Windows is a whole other
problem.

While you can get the info by invoking a process, this seems like a bad
idea because you have the potential to be invoking a lot of processes
rapidly when an error state is repeating. Moreover, external process
management can get scary when we have entered an error state to begin with.
I'm fairly sure that these problems aren't unique to Java.

My approach is to get the values for Linux when I can. Also, I want to
provide any values that are available from the VMs framework.

@dekobon <https://github.com/dekobon> on Linux all the memory info comes
from */proc/meminfo*. MemTotal, MemFree, Buffers and Cached are all entries
in that file. The "free total" is calculated by MemFree+Buffers+Cached. For
now let's just report the system stats (vs. the vm_ stats). Maybe we'll add
vm_ in the future. If you can't get buffers/cached I guess you could just
report zeros for those values, assuming free is the actual total memory
available (just report the same value for free_total so that we have it). I
will also consider making buffers/cached optional so that we can hide them
on our end (zeroing them out is fine for now though).

Regarding the load, OK, let's make five/fifteen optional. I'll update the
schema.

—
Reply to this email directly or view it on GitHub
<https://github.com/honeybadger-io/honeybadger-java/issues/22#issuecomment-145619501>
.
