### ISSUE TITLE
Ignored exceptions cause HoneybadgerSpringExceptionHandler to throw NPEs

### ISSUE THREAD

**Issue by JFL110** [honeybadger-io/honeybadger-java#241]
Hi

I'm using the Java HB error reporter with Spring.

I've found a bug where throwing an exception that is excluded via `excluded_exception_classes` causes an NPE to be thrown from [line 80 in HoneybadgerSpringExceptionHandler](https://github.com/honeybadger-io/honeybadger-java/blob/a6c0c94177865c143363452e3cbdc5b10e7817f4/honeybadger-java/src/main/java/io/honeybadger/reporter/spring/HoneybadgerSpringExceptionHandler.java#L80) because `HoneybadgerReporter.reportError` can return null.

It looks like a simple fix and happy to submit a PR if that would be welcome.

Cheers

**Comment by JamesLeachLumin** [comment]
@joshuap raised https://github.com/honeybadger-io/honeybadger-java/pull/244
