### ISSUE TITLE
DotNet Client

### ISSUE THREAD

**Issue by btecu** [honeybadger-io/honeybadger-java#256]
Is there any plan for a .NET client?

**Comment by joshuap** [comment]
@btecu the best answer I have right now is that we want to build one and have discussed it recently, so there's a good chance it will happen. :grin: I don't have an ETA at the moment, though.

Are you using C#? There is a 3rd-party client [here](https://github.com/webnuts/Honeybadger.ErrorReporter), but it doesn't seem to be maintained.

**Comment by btecu** [comment]
Yes, I'm using C# with `ASP.NET Core`. The third party client is for the legacy `ASP.NET`.

**Comment by subzero10** [comment]
Hey @btecu , can you try this [package](https://github.com/subzero10/honeybadger-dotnet)? It's WIP but I'd love your feedback. Thanks!

**Comment by btecu** [comment]
@subzero10 I no longer work actively on a .NET project.
