### ISSUE TITLE
Identify an application trace

### ISSUE THREAD

**Issue by dekobon** [honeybadger-io/honeybadger-java#3]
I'd need a way to tell that each line of the backtrace either originated in some of the project code rather than an external dependency or Java itself. In Ruby we do this by scanning for the project_root inside each file name, but that obviously won't work in Java.

**Comment by joshuap** [comment]
Here's how we can identify application lines in each backtrace (you can do this for causes, too):

```json
[..., { "number": 1, "file": "foo.java", "method": "Bar", "context": "app" }, ...]
```

All other lines:

```json
[..., { "number": 1, "file": "vendor.java", "method": "Vendor", "context": "all" }, ...]
```

**Comment by dekobon** [comment]
@joshuap I've added this functionality, but I don't notice a change in the UI. Is this expected?

**Comment by dekobon** [comment]
Nevermind. I found it.

**Comment by joshuap** [comment]
looks good!
