### ISSUE TITLE
Does this project use a log4j appender?

### ISSUE THREAD

**Issue by smojtabai** [honeybadger-io/honeybadger-java#33]
I would like to have it hook into that pipeline and report errors.

**Comment by joshuap** [comment]
I believe we do: see [step 2 of the Getting Started guide](https://github.com/honeybadger-io/honeybadger-java#2-install-a-slf4j-compatible-logging-library-or-binding-in-your-project). @dekobon may have some additional input on this.

**Comment by dekobon** [comment]
Hi @smojtabai,

I'm not sure that I understand your question, but I read it as having two possible meanings - *how do I output logs to log4j from the honeybadger library* or *how do I write errors to the honeybadger service that were written as log4j errors*?

**How do I output logs to log4j from the honeybadger library**
If you want to use log4j (v1) to log errors that are sent to the honeybadger reporter library, you will need to use a [slf4j](http://www.slf4j.org/) to log4j adaptor library. There is an explanation of how to set that up [here](http://saltnlight5.blogspot.com/2013/08/how-to-configure-slf4j-with-different.html). If you are using [log4j2](http://logging.apache.org/log4j/2.x/), then it comes with slf4j support out of the box. Also, it is important to note that only the ```HoneybadgerUncaughtExceptionHandler``` and the Spring error handler log directly to logger.error(). All of the other error reporters pass the error on to the underlying framework for logging via the framework.

**How do I write errors to the honeybadger service that were written as log4j errors**
Typically, it is considered an [anti-pattern](https://en.wikipedia.org/wiki/Anti-pattern) to do try catch blocks that swallow exceptions and log to error. An example of that would be the following:

```java

try {
    myObject.myRiskyMethod();
} catch (IOException e) {
    logger.error("My method failed", e);
}
```

What is happening here is that you have logged the error but the flow of program has continued as if nothing has happened. While this is the intended behavior in some cases, it is almost never a good pattern to repeat in a majority of cases. Rather a better approach is to rethrow exceptions or let them bubble up to a global exception handler that handles logging and error reporting like (```HoneybadgerUncaughtExceptionHandler```).

[Here is a great tutorial on Java logging anti-patterns](https://today.java.net/article/2006/04/04/exception-handling-antipatterns#logging).

That said, there is a lot of legacy code that uses this anti-pattern and I have been thinking for some time that it might be advantageous to write a driver for log4j or logback that handles catches logger.error messages and sends them to the honeybadger service as an error. However, this would require writing a custom driver for every logging framework and in Java there are a lot of them that are all widely used - this is why slf4j is so useful. However, slf4j only provides an API for calling the underlying logging driver and doesn't let you configure the underlying driver in any way.
If you want to go down that road you can find documentation on writing a custom log4j driver [here](http://www.javaworld.com/article/2073104/learn-java/write-custom-appenders-for-log4j.html). You would then use the honeybadger-java library inside the driver to send log messages to the honeybadger service.

**Comment by smojtabai** [comment]
The second part is where my question lied. Thank you for the thought out answer. What you are saying makes sense and I see how we can tackle it if we need to.
