### ISSUE TITLE
master README links to 1.0.10 version of jar, but config examples presuppose 1.0.11 or greater

### ISSUE THREAD

**Issue by benissimo** [honeybadger-io/honeybadger-java#42]
And Maven repo lists 1.0.11 as beta.
is 1.1.0 stable?

**Comment by joshuap** [comment]
@benissimo 1.1.0 should bet stable: https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.honeybadger%22%20AND%20a%3A%22honeybadger-java%22

I'll update that link.
