### ISSUE TITLE
Support for custom fingerprint

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-java#423]
Implement custom fingerprint in our java client.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gw141)

**Comment by MaximeAnsquer** [comment]
Hello @subzero10 , from what I see in [the Ruby documentation](https://www.rubydoc.info/gems/honeybadger/Honeybadger/Notice), we just have to add a new field `private String fingerprint` in the class `NoticeDetails.java`, do you agree?
If I submit a pull request, would you be able to review it please?

**Comment by subzero10** [comment]
> Hello @subzero10 , from what I see in [the Ruby documentation](https://www.rubydoc.info/gems/honeybadger/Honeybadger/Notice), we just have to add a new field `private String fingerprint` in the class `NoticeDetails.java`, do you agree? If I submit a pull request, would you be able to review it please?

Sure, go ahead! You will probably want to create a method overload for `reportError()` to be able to pass the `fingerprint` as a parameter.

**Comment by subzero10** [comment]
> Any idea when this could be released?

As soon as we merge the PR :)

**Comment by stympy** [comment]
Thanks, @MaximeAnsquer !
