### ISSUE TITLE
Release v2.0.1 to Maven repository

### ISSUE THREAD

**Issue by sgerrand** [honeybadger-io/honeybadger-java#62]
Now that #61 has been merged and tagged as version 2.0.1, when will it be [released to Maven Central](https://search.maven.org/search?q=g:io.honeybadger)?

**Comment by JasonTrue** [comment]
Thank you for filing this. It looks like I missed a step after closing the release on sonatype. I pressed the release button and it has synced to maven central a few minutes ago, so it should be available now.it may take a bit longer to show up on search. I'll close this issue as soon as I can see it on Maven Central search.

**Comment by JasonTrue** [comment]
It looks like the right version (2.0.1) is showing up as the latest now, so I'll close out this issue. https://search.maven.org/search?q=g:io.honeybadger
